### ISSUE TITLE
multiobjective traveling salesman problem

### ISSUE THREAD

**Issue by wagnerdracha** [pheroh/TSP-GA-PHP#1]
Hello

First of all, congratulations for the initiative. I was looking for something along those lines.

Concerning your work, I would like to ask a question.

Can you tell me if this algorithm works with multiobjective traveling salesman problem?

Thank you

**Comment by pheroh** [comment]
Hello,

As it is now, it only solves for shortest distance. I will be lying if I said I readily know how to change it to work for multiobjectives or how trivial/difficult it's gonna be.
